---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nng-proxy-cfg
  namespace: nng
data:
  nng-proxy.yaml: |
    pub-endpoint: tcp://0.0.0.0:9000
    sub-endpoint: tcp://0.0.0.0:9001
    health-port: 6000
    log-level: 0
